apiVersion: v1
kind: Service
metadata:
  name: kubedemoapp-service1
spec:
  type: NodePort
  selector:
    app: kubedemoapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30181
